bag/urls.py
from django.urls import path
from . import views

app_name = 'bag'

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path(
        'add_to_bag/<int:product_id>/',
        views.add_to_bag,
        name='add_to_bag'
    ),
    path(
        'remove/<int:product_id>/',
        views.remove_from_bag,
        name='remove_from_bag'
    ),
    path(
        'update_quantity/<int:product_id>/',
        views.update_quantity,
        name='update_quantity'
    ),
    path('checkout/', views.checkout, name='checkout'),
    path(
        'create_checkout_session/',
        views.create_checkout_session,
        name='create_checkout_session'
    ),
]

cycleshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import subscribe_newsletter
from django.views.generic import TemplateView
from cycleshop.sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('products/', include('products.urls')),
    path('accounts/', include('allauth.urls')),
    path('bag/', include('bag.urls', namespace='bag')),
    path('search/', views.search_request, name='search_results'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/delete/', views.delete_profile, name='delete_profile'),
    path(
        'subscribe',
        subscribe_newsletter,
        name='subscribe_newsletter'
    ),
    path(
        'checkout/',
        include('checkout.urls', namespace='checkout')
    ),
    path(
        'sitemap.xml',
        TemplateView.as_view(
            template_name="sitemap.xml",
            content_type="application/xml"
        ),
        name='sitemap'
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path(
        'category/<str:category>/',
        views.product_category,
        name='product_category'
    ),

    # Categories
    path('road-bikes/', views.road_bikes, name='road_bikes'),
    path('mountain-bikes/', views.mountain_bikes, name='mountain_bikes'),
    path('electric-bikes/', views.electric_bikes, name='electric_bikes'),
    path('kids-bikes/', views.kids_bikes, name='kids_bikes'),
    path('clothing/', views.clothing, name='clothing'),
    path('accessories/', views.accessories, name='accessories'),
    path('rate/<int:product_id>/', views.rate_product, name='rate_product'),

    # Information pages
    path(
        'return-exchange/',
        views.return_exchange,
        name='return_exchange'
    ),
    path(
        'shipping-information/',
        views.shipping_information,
        name='shipping_information'
    ),
    path('wishlist/', views.view_wishlist, name='wishlist'),
    path(
        'add-to-wishlist/<int:product_id>/',
        views.toggle_wishlist, name='toggle_wishlist'
    ),
    path('faq/', views.faq, name='faq'),

    # Product Management
    path('manage_products/', views.manage_products, name='manage_products'),
    path('add_products/', views.add_product, name='add_product'),
    path(
        'edit_product/<int:product_id>/',
        views.edit_product,
        name='edit_product'
    ),
    path(
        'delete_product/<int:product_id>/',
        views.delete_product,
        name='delete_product'
    ),

    # Wishlist
    path('wishlist/', views.view_wishlist, name='view_wishlist'),
    path(
        'wishlist/add/<int:product_id>/',
        views.add_to_wishlist,
        name='add_to_wishlist'
    ),
    path(
        'wishlist/remove/<int:product_id>/',
        views.remove_from_wishlist,
        name='remove_from_wishlist'
    ),
    path(
        'toggle_wishlist/<int:product_id>/',
        views.toggle_wishlist,
        name='toggle_wishlist'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

cycleshop/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Wishlist
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    """A model to store additional user profile information."""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=100, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    wishlist = models.OneToOneField(
        Wishlist, on_delete=models.CASCADE, null=True, blank=True
    )

    def __str__(self):
        return self.user.username


class NewsletterSubscriber(models.Model):
    """Model to store newsletter subscribers."""
    email = models.EmailField(unique=True)
    date_subscribed = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Create a Profile and Wishlist when a new User is created."""
    if created:
        profile = Profile.objects.create(user=instance)
        wishlist = Wishlist.objects.create(user=instance)
        profile.wishlist = wishlist
        profile.save()

cycleshop/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, NewsletterSubscriber


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, label="Your Name")
    email = forms.EmailField(label="Email address")
    message = forms.CharField(widget=forms.Textarea, label="Your Message")


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'location', 'birth_date']


class NewsletterForm(forms.ModelForm):
    class Meta:
        model = NewsletterSubscriber
        fields = ['email']

cycleshop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ContactForm, UserForm, ProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Profile, NewsletterSubscriber
from products.models import Product


def home(request):
    """A view to return the home page."""
    return render(request, 'cycleshop/home.html')


def contact(request):
    """ A view to handle the contact form submission. """
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Actions like sending an email or saving the form data
            messages.success(
                request,
                'Your message has been successfully sent. '
                'We will get back to you soon!'
            )
            return render(request, 'cycleshop/contact.html')
        else:
            messages.error(
                request,
                'There was an error with your submission. Please try again.'
            )
    else:
        form = ContactForm()

    return render(request, 'cycleshop/contact.html', {'form': form})


def search_request(request):
    """A view to handle search queries and return search results."""
    query = request.GET.get('q', '')

    if query:
        products = Product.objects.filter(name__icontains=query)
    else:
        products = Product.objects.all()

    context = {
        'products': products,
        'query': query,
    }

    return render(request, 'cycleshop/search_results.html', context)


@login_required
def view_profile(request):
    """View the user's profile."""
    profile = request.user.profile
    wishlist = profile.wishlist if profile.wishlist else None

    context = {
        'profile': profile,
        'wishlist': wishlist,
    }
    return render(request, 'profile/view_profile.html', context)


@login_required
def edit_profile(request):
    """View to allow users to edit their profile."""
    profile = get_object_or_404(Profile, user=request.user)

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(
                request,
                'Your profile was successfully updated!'
            )
            return redirect('view_profile')
        messages.error(request, 'Please correct the error below.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)

    return render(
        request,
        'profile/edit_profile.html',
        {'user_form': user_form, 'profile_form': profile_form}
    )


@login_required
def delete_profile(request):
    """View to delete the user's profile."""
    if request.method == 'POST':
        request.user.delete()
        messages.success(
            request,
            'Your profile has been deleted successfully.'
        )
        return redirect('home')

    return render(request, 'profile/delete_profile.html')


def subscribe_newsletter(request):
    """View to handle newsletter subscriptions."""
    if request.method == 'POST':
        email = request.POST.get('email')

        # Check if the email is already subscribed
        if not NewsletterSubscriber.objects.filter(email=email).exists():
            # Create a new subscription
            NewsletterSubscriber.objects.create(email=email)
            messages.success(
                request,
                'You have successfully subscribed to our newsletter.'
            )

            # Redirect to a confirmation page after successful subscription
            return render(
                request,
                'newsletter/newsletter_subscribe_success.html'
            )
        else:
            # Inform the user they are already subscribed
            messages.info(
                request,
                'You are already subscribed to our newsletter.'
            )

    # If the request method is GET or invalid POST data, redirect to home
    return redirect('home')


# Error Handlers
def handler400(request, exception):
    return render(request, 'templates/400.html', status=400)


def handler403(request, exception):
    return render(request, 'templates/403.html', status=403)


def handler404(request, exception):
    return render(request, 'templates/404.html', status=404)


def handler500(request):
    return render(request, 'templates/500.html', status=500)

cycleshop/templates/profile/delete_profile.html
{% extends "base.html" %}
{% block title %}Delete Profile{% endblock %}
{% block content %}
<div class="container">
    <h1>Are you sure you want to delete your profile?</h1>

    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes, Delete My Profile</button>
        <a href="{% url 'view_profile' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

cycleshop/templates/profile/edit_profile.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% block hero %}{% endblock hero %}

{% block title %}Edit Profile{% endblock %}
{% block content %}
<div class="container">
    <h1>Edit Your Profile</h1>

    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{ user_form|crispy }}
        </div>
        <div class="form-group">
            {{ profile_form|crispy }}
        </div>
        <button type="submit" class="btn btn-primary">Save Changes</button>
    </form>
</div>
{% endblock %}

cycleshop/templates/profile/view_profile.html
{% extends "base.html" %}

{% load static %}

{% block hero %}{% endblock hero %}

{% block title %}Profile - CycleShop{% endblock %}

{% block content %}
<div class="container my-5">
    <h1>Profile Details</h1>
    <p><strong>Username:</strong> {{ profile.user.username }}</p>
    <p><strong>Email:</strong> {{ profile.user.email }}</p>
    <p><strong>Location:</strong> {{ profile.location }}</p>
    <p><strong>Birth Date:</strong> {{ profile.birth_date }}</p>
    <p><strong>Bio:</strong> {{ profile.bio }}</p>

    <hr>

    <h2>My Wishlist</h2>

    {% if wishlist and wishlist.products.all %}
        <div class="row">
            {% for product in wishlist.products.all %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        {% if product.image %}
                            <img src="{{ product.image.url }}" class="card-img-top img-fluid" alt="{{ product.name }}">
                        {% else %}
                            <img src="{% static 'images/default_product.jpg' %}" class="card-img-top img-fluid" alt="{{ product.name }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p><strong>Price: €{{ product.price }}</strong></p>
                            <!-- Button to view product -->
                            <a href="{% url 'products:product_detail' product.id %}" class="btn btn-primary">View Product</a>

                            <!-- Button to delete from wishlist -->
                            <form action="{% url 'products:toggle_wishlist' product.id %}" method="post" class="mt-2">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Remove from Wishlist</button>
                            </form>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Your wishlist is empty.</p>
    {% endif %}

    <a href="{% url 'edit_profile' %}" class="btn">Edit Profile</a>
    <a href="{% url 'delete_profile' %}" class="btn-delete btn-danger">Delete Profile</a>
</div>
{% endblock %}